# Generated by Django 5.2.5 on 2025-08-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityclasses',
            name='year',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
