# Generated by Django 5.2.4 on 2025-08-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=60)),
                ('Last_Name', models.CharField(default='', max_length=60)),
                ('Email', models.CharField(default='', max_length=60)),
                ('Username', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
