# Generated by Django 5.2.4 on 2025-08-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.')], default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='Email',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='First_Name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='Last_Name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
