# Generated by Django 5.2.4 on 2025-08-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181101_2355'),
        ('products', '0003_alter_product_type'),
    ]

    operations = [
    ]
